language: go

# Allow use in forks
go_import_path: github.com/tinder-edwardowens/mockery

go:
  - 1.9.x
  - "1.10.x"
  - tip

before_script:
  - go get ./...
  # This package is used in tests only, so "go get" misses it
  - go get github.com/stretchr/testify/assert
